### ISSUE TITLE
Tableview and Scrollview below navigationbar

### ISSUE THREAD

**Issue by PratikHyperlink** [ahmetkgunay/AKGPushAnimator#2]
![simulator screen shot 12-may-2017 6 09 32 pm](https://cloud.githubusercontent.com/assets/14953073/25998528/094f13e4-373f-11e7-8e9e-0f91b29cc1e3.png)

I phasing issue of view under the navigation bar for table view and scroll view. If I am not applied navigationController delegate the then it's working fine. But applies delegate for navigationController to use swipe back functionality then the only issue is generating. 
Please help me..!
Thanks in advance.

**Comment by ahmetkgunay** [comment]
I created a Demo Project With TableView and it works fine with tableview also. I guess your problem is about setting tableview's constraints wrong. 

I added new example project which is using tableview. You can check it out.
